[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]

[phases.optimize]
cmds = ["npm prune --production"]

[start]
cmd = "npm start"